### ISSUE TITLE
Undefined method cast_value for nil:NilClass (Upgrading from rails 6.0.3.4 to 6.1.0)

### ISSUE THREAD

**Issue by recurser** [ankane/active_median#11]
Thanks for the great gem! I'm not sure if this is specific to my usage, but all of my `active_median`-related tests break when I upgrade Rails to `6.1.0`. Specifically here:

https://github.com/ankane/active_median/blob/e453f62106431dac35ef731a62950912063792f3/lib/active_median/model.rb#L75

```
NoMethodError:
  undefined method `cast_value' for nil:NilClass
# ./.bundle/gems/active_median-0.2.5/lib/active_median/model.rb:80:in `block (2 levels) in percentile'
# ./.bundle/gems/active_median-0.2.5/lib/active_median/model.rb:77:in `each'
# ./.bundle/gems/active_median-0.2.5/lib/active_median/model.rb:77:in `each_with_index'
# ./.bundle/gems/active_median-0.2.5/lib/active_median/model.rb:77:in `each'
# ./.bundle/gems/active_median-0.2.5/lib/active_median/model.rb:77:in `map'
# ./.bundle/gems/active_median-0.2.5/lib/active_median/model.rb:77:in `block in percentile'
# ./.bundle/gems/active_median-0.2.5/lib/active_median/model.rb:76:in `each'
# ./.bundle/gems/active_median-0.2.5/lib/active_median/model.rb:76:in `percentile'
# ./.bundle/gems/active_median-0.2.5/lib/active_median/model.rb:4:in `median'
# ./.bundle/gems/active_median-0.2.5/lib/active_median/enumerable.rb:5:in `block in median'
# ./.bundle/gems/active_median-0.2.5/lib/active_median/enumerable.rb:5:in `median'
```

Adding some debugging, `result.column_types` looks like this under `v6.0.3.4`:

```
{"repository_id"=>#<ActiveRecord::ConnectionAdapters::PostgreSQL::OID::Uuid:0x00007fd5d779b5a8 @precision=nil, @scale=nil, @limit=nil>, "percentile_cont"=>#<ActiveModel::Type::Float:0x00007fd5d77a0828 @precision=nil, @scale=nil, @limit=nil>}
```

After upgrading to `6.1.0`, the entry for `percentile_cont` is missing, and `result.column_types` looks like this:

```
{"repository_id"=>#<ActiveRecord::ConnectionAdapters::PostgreSQL::OID::Uuid:0x00007fd05660c7e0 @precision=nil, @scale=nil, @limit=nil>}
```

I'm still trying to narrow things down further, but I was wondering if you had any ideas @ankane ?

**Comment by ankane** [comment]
Hey @recurser, thanks for reporting! Give master a shot (had to make a similar change for other projects and missed it here).

**Comment by recurser** [comment]
@ankane thanks for the quick fix! `master` works great 👍
