### ISSUE TITLE
PG::UndefinedFunction ERROR function percentile_cont does not exist

### ISSUE THREAD

**Issue by sscirrus** [ankane/active_median#14]
I have a table called `Order` and I'm trying to determine all 100 percentiles for `Order.weight`.

Here's my code (apologies if there's a much cleaner way to do this!):

    100.times do |p|
      weight_percentiles << Order.percentile(:weight_lb, p/100.0)
    end

When I run this code, I get:

```
(0.7ms)  SELECT PERCENTILE_CONT(0.95) WITHIN GROUP (ORDER BY "orders"."weight_lb") AS percentile_weight_lb FROM "orders"
/Users/me/.rvm/gems/ruby-3.1.2/gems/rack-mini-profiler-2.3.4/lib/patches/db/pg.rb:69:in `exec_params': PG::UndefinedFunction: ERROR:  function percentile_cont(numeric, character varying) does not exist (ActiveRecord::StatementInvalid)
LINE 1: SELECT PERCENTILE_CONT(0.95) WITHIN GROUP (ORDER BY "order...                          
               ^                                                                                 
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
/Users/me/.rvm/gems/ruby-3.1.2/gems/rack-mini-profiler-2.3.4/lib/patches/db/pg.rb:69:in `exec_params': ERROR:  function percentile_cont(numeric, character varying) does not exist (PG::UndefinedFunction)
LINE 1: SELECT PERCENTILE_CONT(0.95) WITHIN GROUP (ORDER BY "order...                          
               ^                                                                                 
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
```

Any idea how to resolve this?

**Comment by ankane** [comment]
Hi @sscirrus, make sure you're on Postgres 9.4+ and the database user has permission to use that function.

**Comment by sscirrus** [comment]
Hi @ankane, I'm using PostgreSQL 14.6:

```
db_development=# SELECT version();
                                                      version                                                      
-------------------------------------------------------------------------------------------------------------------
 PostgreSQL 14.6 on aarch64-apple-darwin20.6.0, compiled by Apple clang version 12.0.5 (clang-1205.0.22.9), 64-bit
(1 row)
```

My user has the roles `Superuser, Create role, Create DB`.

**Comment by ankane** [comment]
My bad, I misunderstood the error message. It looks like the `weight_lb` column is a `character varying` (string) type instead of a numeric type.

**Comment by ankane** [comment]
You can cast it with:

```ruby
Order.percentile(Arel.sql("weight_lb::float8"), p/100.0)
```
