### ISSUE TITLE
PG::GroupingError: ERROR:  column "foo" must appear in the GROUP BY clause or be used in an aggregate function

### ISSUE THREAD

**Issue by fsateler** [ankane/active_median#9]
It appears ActiveMedian is not generating correct sql when `includes` and `references` are used. The following test fails on current master:

```ruby
  def test_references
    user = User.create!
    user.posts.create!(comments_count: 1)
    assert_equal 1, User.includes(:posts).references(:posts).median(:comments_count)
  end
```

```
  1) Error:
TestActiveMedian#test_references:
ActiveRecord::StatementInvalid: PG::GroupingError: ERROR:  column "users.id" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: ...ONT(0.50) WITHIN GROUP (ORDER BY comments_count), "users"."i...
                                                             ^
: SELECT PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY comments_count), "users"."id" AS t0_r0, "users"."visits_count" AS t0_r1, "users"."latitude" AS t0_r2, "users"."rating" AS t0_r3, "users"."name" AS t0_r4, "users"."created_at" AS t0_r5, "posts"."id" AS t1_r0, "posts"."user_id" AS t1_r1, "posts"."comments_count" AS t1_r2 FROM "users" LEFT OUTER JOIN "posts" ON "posts"."user_id" = "users"."id"
    /tmp/active_median/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/postgresql_adapter.rb:611:in `async_exec'
    /tmp/active_median/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/postgresql_adapter.rb:611:in `block (2 levels) in exec_no_cache'
    /tmp/active_median/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
    /tmp/active_median/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
    /tmp/active_median/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
    /tmp/active_median/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/postgresql_adapter.rb:610:in `block in exec_no_cache'
    /tmp/active_median/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract_adapter.rb:581:in `block (2 levels) in log'
    /usr/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
    /tmp/active_median/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract_adapter.rb:580:in `block in log'
    /tmp/active_median/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
    /tmp/active_median/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract_adapter.rb:571:in `log'
    /tmp/active_median/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/postgresql_adapter.rb:609:in `exec_no_cache'
    /tmp/active_median/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/postgresql_adapter.rb:596:in `execute_and_clear'
    /tmp/active_median/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/postgresql/database_statements.rb:81:in `exec_query'
    /tmp/active_median/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:478:in `select'
    /tmp/active_median/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:70:in `select_all'
    /tmp/active_median/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/query_cache.rb:106:in `select_all'
    /tmp/active_median/lib/active_median/model.rb:37:in `median'
    /tmp/active_median/lib/active_median/enumerable.rb:5:in `block in median'
    /tmp/active_median/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/relation.rb:281:in `scoping'
    /tmp/active_median/lib/active_median/enumerable.rb:5:in `median'
    /tmp/active_median/test/active_median_test.rb:69:in `test_references'
```

It appears all of the columns are added after the `WITHIN GROUP` part.

Thanks for this awesome gem.

**Comment by fsateler** [comment]
`eager_load` appears to have the same effect.

**Comment by ankane** [comment]
Hey @fsateler, thanks for reporting 👍 It looks like it's due to [this issue](https://github.com/rails/rails/issues/21578). Unfortunately, I don't know of a way around it. Ideally, `median` would behave like the other aggregate functions like `count` and `sum`, but I'm not sure it's possible with the current behavior of Active Record.

**Comment by ankane** [comment]
You should be able to use `User.left_outer_joins(:posts)` to produce the same result as `User.includes(:posts).references(:posts)`.
